#
#	GeoPIXE off-line analysis config parameters:
#
# paths
#	'data is the default path for raw data (may be the same as 'analysis')
#	'analysis' is the default path for reduced data, post analysis
#
	path	data		/data/xfm/
	path	analysis	/data/xfm/
	path	config		/data/xfm/config/geopixe_config/
#
# Defaults
#
	default device		MAIA_DEVICE	# default device for Import, etc.
#
# cluster parameters
#	Computer cluster parameters to use when cluster check-boxes are selected
#
#	'CWS' is the CSIRO cluster services for Windows and Linux
#	'cores' uses multiple cores on a single computer
#
	cluster	type		cores		# use 'CWS' or 'cores'
	cluster	nodes		24		# number of nodes to use
#
# CWS config parameters?
#
#
# KVS (for use with Maia Mapper)
#
	kvs	enable		0
	kvs	endpoint	?
	kvs	prefix		?
#
# startup
#	flags windows to open after GeoPIXE is started
#
	startup	image_clone	0		# Extra clone of image window
	startup	regions		1		# image regions window
	startup	spectrum	1		# spectrum display
	startup	identify	1		# X-ray line identification window
	startup	fit		1		# Xray spectrum fit
	startup	sort		1		# Sort EVT window
	startup select		1		# Spectrum select window
#
# manual origin
#	only set auto off(=0) for old data that does not have built-in origin data
#	(remember to set auto=1 again for new data processing!)

	origin	auto		1		# normally auto is on (=1)
	origin	x		0.0		# set manual origin for old data
	origin	y		0.0		# (pre-2010)
#
# Custom
#	custom enable 		1		# enables custom extensions
#	custom lab		XFM
#	custom path		/user/home/
#	custom file		export.csv
#
